In [1]:
import numpy as np

In [3]:
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.11,-13.1,-1]])
b = np.array([1.12,3.44,2.15,4.16])
print(A,b)
n = len(b)
x = np.zeros(n)

# Row-echelon form

for k in range(0,n-1):
    for i in range(k+1,n):
        mult = A[i][k]/A[k][k]
        for j in range(k,n):
            A[i][j] = A[i][j]-(mult)*A[k][j]
        b[i] = b[i]-(mult)* b[k]
print(A,'\n b =',b)
x[n-1] = b[n-1]/A[n-1,n-1]

for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n):
        sum = sum-A[i,j]*x[j]
    x[i] = sum/A[i,i]
print('x =',x)

[[   1.19     2.11  -100.       1.   ]
 [  14.2     -0.122   12.2     -1.   ]
 [   0.     100.     -99.9      1.   ]
 [  15.3      0.11   -13.1     -1.   ]] [1.12 3.44 2.15 4.16]
[[ 1.19000000e+00  2.11000000e+00 -1.00000000e+02  1.00000000e+00]
 [ 0.00000000e+00 -2.53001513e+01  1.20547731e+03 -1.29327731e+01]
 [ 0.00000000e+00  0.00000000e+00  4.66480397e+03 -5.01173747e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.04328072e-01]] 
 b = [  1.12        -9.92470588 -37.07785196   0.24164015]
x = [ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]


In [6]:
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.11,-13.1,-1]])
b = np.array([1.12,3.44,2.15,4.16])
print(A,b)
n = len(b)
x = np.zeros(n)
Ax = np.zeros(n)
r = np.array([1, 0, 0,0])
r_norm = np.linalg.norm(r)
y = np.zeros(n)
while(r_norm >= 10**(-3)):
    for k in range(0,n-1):
        for i in range(k+1,n):
            mult = A[i][k]/A[k][k]
            for j in range(k,n):
                A[i][j] = A[i][j]-(mult)*A[k][j]
            b[i] = b[i]-(mult)* b[k]
    print('A =',A,'\n b =',b)
    x[n-1] = b[n-1]/A[n-1,n-1]
    for i in range(n-2,-1,-1):
        sum = b[i]
        for j in range(i+1,n):
            sum = sum-A[i,j]*x[j]
        x[i] = sum/A[i,i]

    #Finding the value of Ax
    for i in range(len(A)):
        for j in range(len(b)):
            Ax[i] = Ax[i]+A[i,j]*x[j]
    r = b-Ax
    r_norm = np.linalg.norm(r)
    print('r_norm =',r_norm,'\nr =',r)
    b = r
    x = x+y
    y = x
    print('x =',x)

[[   1.19     2.11  -100.       1.   ]
 [  14.2     -0.122   12.2     -1.   ]
 [   0.     100.     -99.9      1.   ]
 [  15.3      0.11   -13.1     -1.   ]] [1.12 3.44 2.15 4.16]
A = [[ 1.19000000e+00  2.11000000e+00 -1.00000000e+02  1.00000000e+00]
 [ 0.00000000e+00 -2.53001513e+01  1.20547731e+03 -1.29327731e+01]
 [ 0.00000000e+00  0.00000000e+00  4.66480397e+03 -5.01173747e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.04328072e-01]] 
 b = [  1.12        -9.92470588 -37.07785196   0.24164015]
r_norm = 0.0 
r = [0. 0. 0. 0.]
x = [ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]


In [7]:
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.11,-13.1,-1]])
b = np.array([1.12,3.44,2.15,4.16])
print(A,b)
n = len(b)
x = np.zeros(n)
for k in range(0,n):
    for i in range(0,n):
        if(k!= i):
            mult = A[i][k]/A[k][k]
            for j in range(k,n):
                A[i][j] = A[i][j]-(mult)*A[k][j]
            b[i] = b[i]-(mult)*b[k]
print('A =',A,'\nb =',b)

for i in range(n-1,-1,-1):
    x[i] = b[i]/A[i,i]
print('x =',x)

[[   1.19     2.11  -100.       1.   ]
 [  14.2     -0.122   12.2     -1.   ]
 [   0.     100.     -99.9      1.   ]
 [  15.3      0.11   -13.1     -1.   ]] [1.12 3.44 2.15 4.16]
A = [[ 1.19000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.53001513e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  4.66480397e+03  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.04328072e-01]] 
b = [  0.2104221   -0.321127   -96.34709503   0.24164015]
x = [ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]
