In [2]:
import numpy as np

## Question 1

In [4]:
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.11,-13.1,-1]])
b = np.array([1.12,3.44,2.15,4.16])
L = np.array([[1,0,0,0],[0,1.0,0,0],[0,0,1,0],[0,0,0,1]])
print(A,b)
n = len(b)
x = np.zeros(n)

# Row echelon form

for k in range(0,n-1):
    for i in range(k+1,n):
        mult = A[i][k]/A[k][k]
        L[i,k] = mult
        for j in range(k,n):
            A[i][j] = A[i][j]-(mult)*A[k][j]
print('U =',A,'\nL =',L, '\nb =',b)

# Ly = b to find y

x[0] = b[0]/L[0,0]
for i in range(1,n):
    sum = b[i]
    for j in range(0,i):
        sum = sum-L[i,j]*x[j]
    x[i] = sum/L[i,i]
b = x
print('y =',b)

#  Ux = y to find x

x[n-1] = b[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n):
        sum = sum-A[i,j]*x[j]
    x[i] = sum/A[i,i]
print('x =',x)

[[   1.19     2.11  -100.       1.   ]
 [  14.2     -0.122   12.2     -1.   ]
 [   0.     100.     -99.9      1.   ]
 [  15.3      0.11   -13.1     -1.   ]] [1.12 3.44 2.15 4.16]
U = [[ 1.19000000e+00  2.11000000e+00 -1.00000000e+02  1.00000000e+00]
 [ 0.00000000e+00 -2.53001513e+01  1.20547731e+03 -1.29327731e+01]
 [ 0.00000000e+00  0.00000000e+00  4.66480397e+03 -5.01173747e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.04328072e-01]] 
L = [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.19327731e+01  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -3.95254554e+00  1.00000000e+00  0.00000000e+00]
 [ 1.28571429e+01  1.06792134e+00 -3.15997398e-03  1.00000000e+00]] 
b = [1.12 3.44 2.15 4.16]
y = [  1.12        -9.92470588 -37.07785196   0.24164015]
x = [ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]


## Question 2

In [6]:
A = np.array([[1.19,2.11,-100,1],[14.2,-0.122,12.2,-1],[0,100,-99.9,1],[15.3,0.11,-13.1,-1]])
b = np.array([1.12,3.44,2.15,4.16])
print(A,b)
n = len(b)
x = np.zeros(n)

# Row echelon form

for k in range(0,n-1):
    for i in range(k+1,n):
        mult = A[i][k]/A[k][k]
        for j in range(k,n):
            A[i][j] = A[i][j]-(mult)*A[k][j]
        A[i,k] = mult
print('A =',A, 'b =',b)

# Ly = b to find y

x[0] = b[0]
for i in range(1,n):
    sum = b[i]
    for j in range(0,i):
        sum = sum-A[i,j]*x[j]
    x[i] = sum
b = x
print('y =',b)

# Ux = y to find x

x[n-1] = b[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n):
        sum = sum-A[i,j]*x[j]
    x[i] = sum/A[i,i]
print('x =',x)

[[   1.19     2.11  -100.       1.   ]
 [  14.2     -0.122   12.2     -1.   ]
 [   0.     100.     -99.9      1.   ]
 [  15.3      0.11   -13.1     -1.   ]] [1.12 3.44 2.15 4.16]
A = [[ 1.19000000e+00  2.11000000e+00 -1.00000000e+02  1.00000000e+00]
 [ 1.19327731e+01 -2.53001513e+01  1.20547731e+03 -1.29327731e+01]
 [ 0.00000000e+00 -3.95254554e+00  4.66480397e+03 -5.01173747e+01]
 [ 1.28571429e+01  1.06792134e+00 -3.15997398e-03 -2.04328072e-01]] b = [1.12 3.44 2.15 4.16]
y = [  1.12        -9.92470588 -37.07785196   0.24164015]
x = [ 0.1768253   0.01269269 -0.02065405 -1.1826087 ]


In [ ]:
x[m,a] = k0
