In [2]:
import numpy as np

## Gauss Elimination

In [5]:
A = np.array([[6,-2,2,4],[12,-4,6,10],[3,-13,9,3],[-6,4,1,-18]],dtype = 'float64')
b = np.array([16,30,-19,-34],dtype = 'float64')
print('A =\n',A,'\nb =',b)
n = len(b)
x = np.zeros(n)

# Row echelon form

for k in range(0,n-1):
    max_index = np.argmax(abs(A[k:n,k])) + k
    print('Max_index =',max_index)
    A[[max_index,k]] = A[[k,max_index]]
    b[[max_index,k]] = b[[k,max_index]]
    print('Pivot Matrix A =',A) 
    
    #Printing Pivot Matrix

    for i in range(k+1,n):
        mult = A[i,k]/A[k,k]
        for j in range(k,n):
            A[i,j] = A[i,j]-(mult)*A[k,j]
        b[i] = b[i]-(mult)* b[k]
print('A =\n',A,'\nb =',b)

x[n-1]=b[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n):
        sum = sum-A[i,j]*x[j]
    x[i] = sum/A[i,i]
print('x =',x)

A =
 [[  6.  -2.   2.   4.]
 [ 12.  -4.   6.  10.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]] 
b = [ 16.  30. -19. -34.]
Max_index = 1
Pivot Matrix A = [[ 12.  -4.   6.  10.]
 [  6.  -2.   2.   4.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]]
Max_index = 2
Pivot Matrix A = [[ 12.   -4.    6.   10. ]
 [  0.  -12.    7.5   0.5]
 [  0.    0.   -1.   -1. ]
 [  0.    2.    4.  -13. ]]
Max_index = 3
Pivot Matrix A = [[ 12.          -4.           6.          10.        ]
 [  0.         -12.           7.5          0.5       ]
 [  0.           0.           5.25       -12.91666667]
 [  0.           0.          -1.          -1.        ]]
A =
 [[ 12.          -4.           6.          10.        ]
 [  0.         -12.           7.5          0.5       ]
 [  0.           0.           5.25       -12.91666667]
 [  0.           0.           0.          -3.46031746]] 
b = [ 30.         -26.5        -23.41666667  -3.46031746]
x = [ 3.  1. -2.  1.]


## Gauss Jordan

In [6]:
A = np.array([[6,-2,2,4],[12,-4,6,10],[3,-13,9,3],[-6,4,1,-18]],dtype = 'float64')
b = np.array([16,30,-19,-34],dtype = 'float64')
print('A =\n',A,'\nb =',b)
n = len(b)
x = np.zeros(n)
for k in range(0,n):
    max_index = np.argmax(abs(A[k:n,k])) + k
    print('Max_index =',max_index)
    A[[max_index,k]] = A[[k,max_index]]
    b[[max_index,k]] = b[[k,max_index]]
    print('Pivot Matrix A=\n',A) 
    
    # Printing Pivot Matrix

    for i in range(0,n):
        if(k!=i):
            mult = A[i][k]/A[k][k]
            for j in range(k,n):
                A[i][j] = A[i][j]-(mult)*A[k][j]
            b[i] = b[i]-(mult)*b[k]
print('A =',A,'\nb =',b)

for i in range(n-1,-1,-1):
    x[i] = b[i]/A[i,i]
print('x =',x)

A =
 [[  6.  -2.   2.   4.]
 [ 12.  -4.   6.  10.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]] 
b = [ 16.  30. -19. -34.]
Max_index = 1
Pivot Matrix A=
 [[ 12.  -4.   6.  10.]
 [  6.  -2.   2.   4.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]]
Max_index = 2
Pivot Matrix A=
 [[ 12.   -4.    6.   10. ]
 [  0.  -12.    7.5   0.5]
 [  0.    0.   -1.   -1. ]
 [  0.    2.    4.  -13. ]]
Max_index = 3
Pivot Matrix A=
 [[ 12.           0.           3.5          9.83333333]
 [  0.         -12.           7.5          0.5       ]
 [  0.           0.           5.25       -12.91666667]
 [  0.           0.          -1.          -1.        ]]
Max_index = 3
Pivot Matrix A=
 [[ 12.           0.           0.          18.44444444]
 [  0.         -12.           0.          18.95238095]
 [  0.           0.           5.25       -12.91666667]
 [  0.           0.           0.          -3.46031746]]
A = [[ 12.           0.           0.           0.        ]
 [  0.         -12.           0.           0.   

## LU Decomposition with Extra Space

In [8]:
A = np.array([[6,-2,2,4],[12,-4,6,10],[3,-13,9,3],[-6,4,1,-18]],dtype='float64')
b = np.array([16,30,-19,-34],dtype='float64')
L = np.array([[1,0,0,0],[0,1.0,0,0],[0,0,1,0],[0,0,0,1]])
U = A
print('A =\n',A,'\nb =',b)
n = len(b)
x = np.zeros(n)

# Row echelon form

for k in range(0,n-1):
    max_index = np.argmax(abs(A[k:n,k])) + k
    print('Max_index =',max_index)
    A[[max_index,k]] = A[[k,max_index]]
    b[[max_index,k]] = b[[k,max_index]]
    L[[max_index,k]] = L[[k,max_index]]
    L[:,[max_index,k]] = L[:,[k,max_index]]
    print('Pivot Matrix A =\n',A) 
    
    # Printing Pivot Matrix
    
    for i in range(k+1,n):
        mult = A[i][k]/A[k][k]
        L[i,k] = mult
        for j in range(k,n):
            A[i][j] = A[i][j]-(mult)*A[k][j]
A = U
U = A
print('U =\n',U,'\nL =\n',L, '\nb =',b)

# Forward Substitution Ly=b to find y

x[0] = b[0]/L[0,0]
for i in range(1,n):
    sum = b[i]
    for j in range(0,i):
        sum = sum-L[i,j]*x[j]
        x[i] = sum/L[i,i]
b = x
print('y =',b)

# Backward Substitution Ux=y to find x

x[n-1] = b[n-1]/U[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n):
        sum = sum-U[i,j]*x[j]
    x[i] = sum/U[i,i]
print('x =',x)

A =
 [[  6.  -2.   2.   4.]
 [ 12.  -4.   6.  10.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]] 
b = [ 16.  30. -19. -34.]
Max_index = 1
Pivot Matrix A =
 [[ 12.  -4.   6.  10.]
 [  6.  -2.   2.   4.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]]
Max_index = 2
Pivot Matrix A =
 [[ 12.   -4.    6.   10. ]
 [  0.  -12.    7.5   0.5]
 [  0.    0.   -1.   -1. ]
 [  0.    2.    4.  -13. ]]
Max_index = 3
Pivot Matrix A =
 [[ 12.          -4.           6.          10.        ]
 [  0.         -12.           7.5          0.5       ]
 [  0.           0.           5.25       -12.91666667]
 [  0.           0.          -1.          -1.        ]]
U =
 [[ 12.          -4.           6.          10.        ]
 [  0.         -12.           7.5          0.5       ]
 [  0.           0.           5.25       -12.91666667]
 [  0.           0.           0.          -3.46031746]] 
L =
 [[ 1.          0.          0.          0.        ]
 [ 0.25        1.          0.          0.        ]
 [-0.5        -0.16666

## LU Decomposition without Extra Space

In [3]:
A = np.array([[6,-2,2,4],[12,-4,6,10],[3,-13,9,3],[-6,4,1,-18]],dtype='float64')
b = np.array([16,30,-19,-34],dtype='float64')
print('A =\n',A,'\nb =',b)
n = len(b)
x = np.zeros(n)

# Row echelon form

for k in range(0,n-1):
    max_index = np.argmax(abs(A[k:n,k])) + k
    print('Max_index =',max_index)
    A[[max_index,k]] = A[[k,max_index]]
    b[[max_index,k]] = b[[k,max_index]]
    print('Pivot Matrix A =\n',A) 
    
    # Printing Pivot Matrix
    
    for i in range(k+1,n):
        mult = A[i][k]/A[k][k]
        for j in range(k,n):
            A[i][j] = A[i][j]-(mult)*A[k][j]
        A[i,k] = mult
print('A =\n',A, '\nb =',b)

# Forward Substitution for y

x[0] = b[0]
for i in range(1,n):
    sum = b[i]
    for j in range(0,i):
        sum = sum-A[i,j]*x[j]
    x[i] = sum
b = x 
print('y =',b)

# Backward Substitution for x

x[n-1] = b[n-1]/A[n-1,n-1]
for i in range(n-2,-1,-1):
    sum = b[i]
    for j in range(i+1,n):
        sum = sum-A[i,j]*x[j]
    x[i] = sum/A[i,i]
print('x =',x)

A =
 [[  6.  -2.   2.   4.]
 [ 12.  -4.   6.  10.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]] 
b = [ 16.  30. -19. -34.]
Max_index = 1
Pivot Matrix A =
 [[ 12.  -4.   6.  10.]
 [  6.  -2.   2.   4.]
 [  3. -13.   9.   3.]
 [ -6.   4.   1. -18.]]
Max_index = 2
Pivot Matrix A =
 [[ 12.    -4.     6.    10.  ]
 [  0.25 -12.     7.5    0.5 ]
 [  0.5    0.    -1.    -1.  ]
 [ -0.5    2.     4.   -13.  ]]
Max_index = 3
Pivot Matrix A =
 [[ 12.          -4.           6.          10.        ]
 [  0.25       -12.           7.5          0.5       ]
 [ -0.5         -0.16666667   5.25       -12.91666667]
 [  0.5         -0.          -1.          -1.        ]]
A =
 [[ 12.          -4.           6.          10.        ]
 [  0.25       -12.           7.5          0.5       ]
 [ -0.5         -0.16666667   5.25       -12.91666667]
 [  0.5         -0.          -0.19047619  -3.46031746]] 
b = [ 30. -19. -34.  16.]
y = [ 30.         -26.5        -23.41666667  -3.46031746]
x = [ 3.  1. -2.  1.]
